import { Product } from "./models/product";

let products = [
    new Product(new URL("https://imgur.com/a/wLShfuG"), 
    "SAMSUNG Q70B QLED Smart TV",
    "4K",
    "120Hz",
    "65''",
    "5000kr",
    "TV"),
    new Product(new URL("https://imgur.com/a/c6mBJcK"),
    "SHARP 55BL2EA UHD Android TV",
    "4K",
    "50Hz",
    "55''",
    "3000kr",
    "TV"),
    new Product(new URL("https://imgur.com/a/Rg7ld86"),
    "SHARP 43EL4EA Android TV",
    "4K",
    "50Hz",
    "43''",
    "4000kr",
    "TV"),

    new Product(new URL("https://imgur.com/a/M8JTHlj"),
    "MSI Optix G273QF - Gamingskärm",
    "WQHD",
    "165Hz",
    "27''",
    "4000kr",
    "Monitor"),
    new Product(new URL("https://imgur.com/a/GnGLFyR"),
    "AOC 25G3ZM/BK",
    "Full HD",
    "240Hz",
    "24.5''",
    "4500kr",
    "Monitor"),
    new Product(new URL("https://imgur.com/a/GnGLFyR"),
    "ACER Nitro XV272L",
    "Full HD",
    "144Hz",
    "27''",
    "2500kr",
    "Monitor"),
]

console.log(products);
